Repository fga-eps-mds/2020.1-GaiaDex-wiki, pull requests merged in 2020-09, with the labels that each got.

#30 Sprint1 planning
  docs/sprints/sprint1/planning.md
Labels: documentation, eps

#10 Vision Document
  docs/vision_document/vision_document.md
  mkdocs.yml
Labels: documentation

#33 Sprint 0 planning and review / Sprint 1 planning
  docs/sprints/sprint0/img/burndown.png
  docs/sprints/sprint0/img/commits.png
  docs/sprints/sprint0/img/quadroConhecimento.jpg
  docs/sprints/sprint0/planning.md
  docs/sprints/sprint0/results.md
  docs/sprints/sprint1/planning.md
  mkdocs.yml
Labels: documentation, eps

#34 I20 start prototype
  docs/img/prototipo/print1.png
  docs/img/prototipo/print2.png
  docs/img/prototipo/print3.png
  docs/img/prototipo/print4.png
  docs/img/prototipo/print5.png
  docs/prototipo/prototipo.md
Labels: documentation

#13 Roadmaps
  docs/roadmap/product_roadmap.md
  docs/roadmap/roadmap.md
  docs/roadmap/roles_roadmap.md
  mkdocs.yml
Labels: documentation, eps

#41 Add communication plan document
  docs/communication_plan/communication_plan.md
  docs/communication_plan/img/daily.jpg
  docs/communication_plan/img/pontuacao.png
  mkdocs.yml
Labels: documentation, eps

#16 Update product_backlog.md
  docs/product_backlog/acceptance_criteria.md
  docs/product_backlog/add_acceptance_criteria_links.py
  docs/product_backlog/create_acc_criteria_template.py
  docs/product_backlog/product_backlog.md
  docs/product_backlog/sort_by_epics.py
  docs/product_backlog/template_criteria.md
Labels: documentation, eps

#42 Architecture Document
  docs/architecture_document/architecture_document.md
  docs/architecture_document/img/Node.js_logo.svg
  docs/architecture_document/img/class_diagram.png
  docs/architecture_document/img/expo.png
  docs/architecture_document/img/express.png
  docs/architecture_document/img/pkg_back.png
  docs/architecture_document/img/pkg_front.png
  docs/architecture_document/img/react_native.png
  mkdocs.yml
Labels: documentation, eps, mds

#43 Project opening term
  docs/project_opening_term/project_opening_term.md
  mkdocs.yml
Labels: documentation, eps, mds

#35 Add sprint 1 results and sprint 2 review.
  docs/sprints/planning.md
  docs/sprints/results.md
  docs/sprints/sprint0/results.md
  docs/sprints/sprint1/img/burndown.jpg
  docs/sprints/sprint1/img/hours.jpg
  docs/sprints/sprint1/img/knowledge_box.jpg
  docs/sprints/sprint1/img/velocity.jpg
  docs/sprints/sprint1/planning.md
  docs/sprints/sprint1/results.md
  docs/sprints/sprint2/img/pairing.jpg
  docs/sprints/sprint2/planning.md
  mkdocs.yml
Labels: documentation, eps

#44 Risk Management
  docs/risk_management/risk_management.md
  mkdocs.yml
Labels: documentation, eps

#45 Supplementary document
  docs/supplementary_document/supplementary_document.md
  mkdocs.yml
Labels: documentation, eps, mds

#47 Refactor Acceptance Criteria
  docs/product_backlog/acceptance_criteria.md
  docs/product_backlog/create_acc_criteria_template.py
  docs/product_backlog/extras.md
  docs/product_backlog/fix_all.sh
  docs/product_backlog/product_backlog.md
  docs/product_backlog/scripts/add_acceptance_criteria_links.py
  docs/product_backlog/scripts/reorder_acceptance_criteria.py
  docs/product_backlog/scripts/sort_by_epics.py
  docs/product_backlog/template_criteria.md
Labels: documentation, eps

#53 I52 add user stories
  docs/fix_id_us.py
  docs/product_backlog/acceptance_criteria.md
  docs/product_backlog/extras.md
  docs/product_backlog/product_backlog.md
  docs/roadmap/product_roadmap.md
  docs/sprints/sprint2/planning.md
  docs/sprints/sprint2/results.md
  docs/sprints/sprint3/planning.md
Labels: documentation, eps

#51 adicionando 'gerador de issues'
  docs/product_backlog/generate_issues.py
  docs/product_backlog/product_backlog.md
  docs/product_backlog/template_issues.md
Labels: documentation, eps

#64 Review sprint3 and planning sprint4
  docs/product_backlog/potential_backlog/potential_acceptance_criteria.md
  docs/product_backlog/potential_backlog/potential_product_backlog.md
  docs/product_backlog/product_backlog.md
  docs/product_backlog/template_issues.md
  docs/roadmap/product_roadmap.md
  docs/sprints/sprint2/planning.md
  docs/sprints/sprint2/results.md
  docs/sprints/sprint3/img/burndown_sprint3.png
  docs/sprints/sprint3/img/commits_back.png
  docs/sprints/sprint3/img/commits_wiki.png
  docs/sprints/sprint3/img/knowledge_box.png
  docs/sprints/sprint3/img/velocity.png
  docs/sprints/sprint3/planning.md
  docs/sprints/sprint3/results.md
  docs/sprints/sprint4/img/pairing.png
  docs/sprints/sprint4/img/risk_burndown.png
  docs/sprints/sprint4/planning.md
Labels: documentation
