Repository fga-eps-mds/2020.1-GaiaDex-wiki, pull requests merged in 2020-10, with the labels that each got.

#55 Refactor Product Roadmap
  docs/product_backlog/product_backlog.md
  docs/roadmap/product_roadmap.md
Labels: documentation, eps

#87 EVM
  docs/evm/evm.md
  mkdocs.yml
Labels: documentation, enhancement, eps, mds

#90 EAP
  docs/eap/eap.md
  docs/eap/img/eap.jpg
  mkdocs.yml
Labels: documentation

#98 Review sprint 5 and planning sprint 6
  docs/sprints/sprint3/results.md
  docs/sprints/sprint4/planning.md
  docs/sprints/sprint4/results.md
  docs/sprints/sprint5/img/burndown.jpg
  docs/sprints/sprint5/img/hours.png
  docs/sprints/sprint5/img/velocity.jpg
  docs/sprints/sprint5/planning.md
  docs/sprints/sprint5/results.md
  docs/sprints/sprint6/img/GCS_pont.jpg
  docs/sprints/sprint6/img/US01_back.jpg
  docs/sprints/sprint6/img/US02_back.png
  docs/sprints/sprint6/img/US03_back.jpg
  docs/sprints/sprint6/img/pairing.jpg
  docs/sprints/sprint6/img/risk_burndown.jpg
  docs/sprints/sprint6/planning.md
  mkdocs.yml
Labels: documentation, eps

#99 i94, i95, i97 - GCS, Architecture and Product Roadmap
  docs/architecture_document/Class_Diagram0.asta
  docs/architecture_document/architecture_document.md
  docs/architecture_document/img/ClassDiagram.jpg
  docs/gcs/gcs.md
  docs/roadmap/product_roadmap.md
  mkdocs.yml
Labels: documentation, enhancement, eps

#77 Style Guide
  docs/document_style_guide/Nodejs_style_guide.md
  docs/document_style_guide/React_style_guide.md
Labels: documentation

#107 adding review (sprint 6) and planning (sprint 7)
  .github/ISSUE_TEMPLATE/basic-issue-template.md
  docs/sprints/sprint5/img/commits_wiki_sprint5.png
  docs/sprints/sprint5/results.md
  docs/sprints/sprint6/img/burndown.png
  docs/sprints/sprint6/img/commits_back_sprint6.png
  docs/sprints/sprint6/img/commits_wiki_sprint6.png
  docs/sprints/sprint6/img/hours.png
  docs/sprints/sprint6/img/knowledge_box.png
  docs/sprints/sprint6/img/velocity.png
  docs/sprints/sprint6/meeting_minutes.md
  docs/sprints/sprint6/planning.md
  docs/sprints/sprint6/results.md
  docs/sprints/sprint7/img/pairings.png
  docs/sprints/sprint7/img/pont_codeclimate.png
  docs/sprints/sprint7/img/pont_lint.png
  docs/sprints/sprint7/img/pont_tests.png
  docs/sprints/sprint7/img/pont_us15.png
  docs/sprints/sprint7/img/pont_us16.png
  docs/sprints/sprint7/img/pont_us17.png
  docs/sprints/sprint7/img/pont_us18.png
  docs/sprints/sprint7/img/risk_burndown.JPG
  docs/sprints/sprint7/meeting_minutes.md
  docs/sprints/sprint7/planning.md
  docs/sprints/sprint7/results.md
  docs/sprints/template/meeting_minutes.md
  docs/sprints/template/planning.md
  docs/sprints/template/results.md
  mkdocs.yml
Labels: documentation, hacktoberfest-accepted

#114 adding post mortem
  docs/post_mortem/post_mortem.md
Labels: hacktoberfest-accepted

#110 adding gh actions to update mkdocs automatically
  .github/workflows/main.yml
  .gitignore
  docs/document_style_guide/Nodejs_style_guide.md
  docs/document_style_guide/React_style_guide.md
  docs/fix_id_us.py
  docs/index.md
  docs/product_backlog/generate_issues.py
  docs/product_backlog/potential_backlog/potential_acceptance_criteria.md
  docs/product_backlog/potential_backlog/potential_extra_criterias.md
  docs/product_backlog/potential_backlog/potential_product_backlog.md
  docs/product_backlog/product_backlog.md
  docs/product_backlog/scripts/add_acceptance_criteria_links.py
  docs/product_backlog/scripts/reorder_acceptance_criteria.py
  docs/product_backlog/scripts/sort_by_epics.py
  docs/roadmap/product_roadmap.md
  docs/roadmap/roles_roadmap.md
  docs/sprints/sprint7/planning.md
  docs/sprints/sprint7/results.md
  docs/vision_document/ZeBrand.md
  docs/visual_identity/inspirations.md
  mkdocs.yml
  requirements.txt
  update_mkdocs_yml.py
Labels: hacktoberfest-accepted

#116 Review sprint7 planning sprint8
  .gitignore
  docs/generate_sprints_from_template.py
  docs/generate_sprints_from_template.sh
  docs/roadmap/product_roadmap.md
  docs/sprints/sprint10/meeting_minutes.md
  docs/sprints/sprint10/planning.md
  docs/sprints/sprint11/meeting_minutes.md
  docs/sprints/sprint11/planning.md
  docs/sprints/sprint12/meeting_minutes.md
  docs/sprints/sprint12/planning.md
  docs/sprints/sprint13/meeting_minutes.md
  docs/sprints/sprint13/planning.md
  docs/sprints/sprint14/meeting_minutes.md
  docs/sprints/sprint14/planning.md
  docs/sprints/sprint7/img/commits_wiki_sprint7.png
  docs/sprints/sprint7/img/hours_sprint7.png
  docs/sprints/sprint7/img/knowledge_sprint7.png
  docs/sprints/sprint7/img/velocity_sprint7.png
  docs/sprints/sprint7/results.md
  docs/sprints/sprint8/img/issues_sprint8.png
  docs/sprints/sprint8/img/pairing_sprint8.png
  docs/sprints/sprint8/img/risk_sprint8.png
  docs/sprints/sprint8/meeting_minutes.md
  docs/sprints/sprint8/planning.md
  docs/sprints/sprint9/meeting_minutes.md
  docs/sprints/sprint9/planning.md
  docs/sprints/template/meeting_minutes.md
Labels: documentation, eps

#118 Atualizar EVM
  docs/sprints/sprint0/img/evm.jpg
  docs/sprints/sprint0/results.md
  docs/sprints/sprint1/img/evm.jpg
  docs/sprints/sprint1/results.md
  docs/sprints/sprint2/img/evm.JPG
  docs/sprints/sprint2/results.md
  docs/sprints/sprint3/img/evm.jpg
  docs/sprints/sprint3/results.md
  docs/sprints/sprint4/img/evm.jpg
  docs/sprints/sprint4/results.md
  docs/sprints/sprint5/img/evm.jpg
  docs/sprints/sprint5/results.md
  docs/sprints/sprint6/img/evm.jpg
  docs/sprints/sprint6/results.md
  docs/sprints/sprint7/img/evm.jpg
  docs/sprints/sprint7/planning.md
  docs/sprints/sprint7/results.md
Labels: documentation, enhancement, eps, hacktoberfest-accepted
